[database]
host = "16.170.143.253"
port = 5432
user = "admin"
password = "password123" # Your actual database password
database = "miva_ai_db"

[auth]
username = "miva_admin"
# This is the SHA-256 hash for the password "password"
# For better security, change the password and generate a new hash
hashed_password = "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8"
